### ISSUE TITLE
Not able to install package with npm version `2`

### ISSUE THREAD

**Issue by JustinBeaudry** [dainis/node-gcstats#26]
```
system npm-test › npm i gc-stats
npm WARN package.json npm-test@1.0.0 No description
npm WARN package.json npm-test@1.0.0 No repository field.
npm WARN package.json npm-test@1.0.0 No README data
/
> gc-stats@1.1.0 install /Users/xxx/Projects/npm-test/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/justinbeaudry/Projects/npm-test/node_modules/gc-stats/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v4.8.0/bin/node" "/Users/xxx/.nvm/versions/node/v4.8.0/bin/npm" "i" "gc-stats"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! gc-stats@1.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gc-stats@1.1.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the gc-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gc-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls gc-stats
npm ERR! There is likely additional logging output above.
```

**Comment by JustinBeaudry** [comment]
This feels related to #25

**Comment by dainis** [comment]
upgrade npm

**Comment by JustinBeaudry** [comment]
Upgrading `npm` works. Would be nice if the engines block in the `package.json` noted that it does not support versions of `npm` earlier than `3`.
