### ISSUE TITLE
won't build for armv8

### ISSUE THREAD

**Issue by dkebler** [dainis/node-gcstats#52]
is this repo designed to build for armv8?  If so looks like I am missing a python module called 'ast'

not a python guru.. If that's the fix how do I get that loaded.  It was apparently already on my dev 86 box so it must in some python dev library.

They say it's a standard library so maybe this arm box never got all of python installed.

https://docs.python.org/3/library/ast.html

```
> gc-stats@1.4.0 install /opt/lights/controller/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@14.6.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
    import ast
ImportError: No module named ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.49-rockchip64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64/gcstats.node" "--module_name=gcstats" "--module_path=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /opt/lights/controller/node_modules/gc-stats
gyp ERR! node -v v14.6.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64/gcstats.node --module_name=gcstats --module_path=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/lights/controller/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.49-rockchip64
node-pre-gyp ERR! command "/usr/bin/node" "/opt/lights/controller/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/lights/controller/node_modules/gc-stats
node-pre-gyp ERR! node -v v14.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64/gcstats.node --module_name=gcstats --module_path=/opt/lights/controller/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-linux-arm64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

**Comment by dkebler** [comment]
I have using a focal 20.04 OS on that box and it looks like it only now loads python 3.8+.  There is no python2. Does this build depend on python2 ???

**Comment by dkebler** [comment]
all is good apparently 20.04 makes no symbolic link for 'python' and node-gyp expects to call python not python3. Luckily it compiles with the python3.8 install on that os image.

see
https://techsparx.com/nodejs/install/bootstrap-drops-jquery.html
